* ExamplePresenters

This repo shows mock/sample presenter xml file format.  Component sites will implement their own version of this repo which will conform to the same format.  The Presenter repo is the root of the ant build for websites.  The Presenter xml files contain descriptive text about datasets which are loaded and displayed as dataset records.
  + [[https://github.com/VEuPathDB/ApiCommonPresenters][ApiCommonPresenters]]
  + [[https://github.com/VEuPathDB/MicrobiomePresenters][MicrobiomePresenters]]
  + [[https://github.com/VEuPathDB/ClinEpiPresenters][ClinEpiPresenters]]

** Dependencies

   + yarn / npm / ant
   + WEBAPP_PROP_FILE file (file with one property for the webapp target directory)
      webappTargetDir=BLAH
   + environment variables for GUS_HOME and PROJECT_HOME
   + Internal Dependencies
     + ApiCommonWebservice, ExampleDatasets

** Installation instructions.

   + bldw ExamplePresenters (for building a website)
   + bld ExamplePresenters/Model (for running tuning manager)

** Operating instructions.

   + building this project will create an VEuPath website

** Manifest

   + Model/lib/xml/datasetPresenters :: one xml file per component project.  elements will match with a dataset record and may optionally specify a java injector class.

